In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
s = pd.Series([1,3,5,np.nan,6,8])
print(s)
type(s)
print(s[0])
(s[s == 5.0]).index[0]

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
1.0


2

In [56]:
dates = pd.date_range('20130101', periods=6)
print(dates)
df = pd.DataFrame(np.random.rand(6,4), index=dates, columns=['A','B','C','D'])
print(df)
print(df.index[0])
print(df['A'][3])
print(df.columns)
print(df.values)


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01  0.688237  0.853622  0.229503  0.885162
2013-01-02  0.199508  0.058591  0.532108  0.820814
2013-01-03  0.341717  0.121374  0.318218  0.717195
2013-01-04  0.585416  0.980827  0.595542  0.941821
2013-01-05  0.718020  0.982208  0.308296  0.827824
2013-01-06  0.679155  0.494271  0.201127  0.795402
2013-01-01 00:00:00
0.5854155671611192
Index(['A', 'B', 'C', 'D'], dtype='object')
[[0.68823682 0.85362212 0.22950299 0.88516225]
 [0.1995084  0.05859063 0.53210842 0.82081363]
 [0.34171712 0.12137446 0.31821844 0.71719537]
 [0.58541557 0.98082742 0.59554163 0.94182099]
 [0.71801991 0.98220836 0.30829599 0.82782362]
 [0.67915531 0.49427068 0.2011271  0.79540175]]
<bound method NDFrame.describe of                    A         B         C         D
2013-01-01  0.688237  0.85362

In [57]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.535342  0.581816  0.364132  0.831370
std    0.214575  0.421150  0.162288  0.076872
min    0.199508  0.058591  0.201127  0.717195
25%    0.402642  0.214599  0.249201  0.801755
50%    0.632285  0.673946  0.313257  0.824319
75%    0.685966  0.949026  0.478636  0.870828
max    0.718020  0.982208  0.595542  0.941821

In [59]:
df.T
print(df)

                   A         B         C         D
2013-01-01  0.688237  0.853622  0.229503  0.885162
2013-01-02  0.199508  0.058591  0.532108  0.820814
2013-01-03  0.341717  0.121374  0.318218  0.717195
2013-01-04  0.585416  0.980827  0.595542  0.941821
2013-01-05  0.718020  0.982208  0.308296  0.827824
2013-01-06  0.679155  0.494271  0.201127  0.795402


In [63]:
df.sort_index(axis=0, ascending=False)

A         B         C         D
2013-01-06  0.679155  0.494271  0.201127  0.795402
2013-01-05  0.718020  0.982208  0.308296  0.827824
2013-01-04  0.585416  0.980827  0.595542  0.941821
2013-01-03  0.341717  0.121374  0.318218  0.717195
2013-01-02  0.199508  0.058591  0.532108  0.820814
2013-01-01  0.688237  0.853622  0.229503  0.885162

In [64]:
df.sort_values(by='B')

A         B         C         D
2013-01-02  0.199508  0.058591  0.532108  0.820814
2013-01-03  0.341717  0.121374  0.318218  0.717195
2013-01-06  0.679155  0.494271  0.201127  0.795402
2013-01-01  0.688237  0.853622  0.229503  0.885162
2013-01-04  0.585416  0.980827  0.595542  0.941821
2013-01-05  0.718020  0.982208  0.308296  0.827824

In [70]:
df.loc['2013-01-02']

A    0.199508
B    0.058591
C    0.532108
D    0.820814
Name: 2013-01-02 00:00:00, dtype: float64

In [72]:
df.loc['2013-01-02',['A','B']]

A    0.199508
B    0.058591
Name: 2013-01-02 00:00:00, dtype: float64

In [74]:
df.loc[:,['A','B']]

A         B
2013-01-01  0.688237  0.853622
2013-01-02  0.199508  0.058591
2013-01-03  0.341717  0.121374
2013-01-04  0.585416  0.980827
2013-01-05  0.718020  0.982208
2013-01-06  0.679155  0.494271

In [75]:
df.iloc[3]

A    0.585416
B    0.980827
C    0.595542
D    0.941821
Name: 2013-01-04 00:00:00, dtype: float64

In [79]:
df.iloc[3:5,0:2]

A         B
2013-01-04  0.585416  0.980827
2013-01-05  0.718020  0.982208

In [80]:
df[df.A > 0]

A         B         C         D
2013-01-01  0.688237  0.853622  0.229503  0.885162
2013-01-02  0.199508  0.058591  0.532108  0.820814
2013-01-03  0.341717  0.121374  0.318218  0.717195
2013-01-04  0.585416  0.980827  0.595542  0.941821
2013-01-05  0.718020  0.982208  0.308296  0.827824
2013-01-06  0.679155  0.494271  0.201127  0.795402

In [102]:
df[df>0]['A'].values

array([0.68823682, 0.1995084 , 0.34171712, 0.58541557, 0.71801991,
       0.67915531])

In [105]:
df[df['A'].]

array([0.68823682, 0.1995084 , 0.34171712, 0.58541557, 0.71801991,
       0.67915531])